const express=require('express')
const app=express()
const bodyParser=require('body-parser')
app.use(express.json())
app.use(bodyParser.json())
const routes=require('./routes')
app.use(routes)
app.listen(3000,()=>console.log('server is running at 3000'))